name: Java CI with Maven

on:
  schedule:
    - cron: "30 0 * * *"  # 6:00 AM IST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Clean Maven cache
      run: rm -rf ~/.m2/repository/org/aspectj/aspectjweaver

    - name: Ensure dependencies are available
      run: mvn dependency:resolve

    - name: Run TestNG XML
      run: mvn clean test -DsuiteXmlFile=testng.xml -Dparallel=methods -DthreadCount=4 -U
