name: Java CI with Maven

on:
  schedule:
    - cron: "30 0 * * *"  # 6:00 AM IST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - uses: actions/checkout@v4

    # Step 2: Set up JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    # Step 3: Run Maven test
    - name: Run Maven Test
      run: |
        mvn clean test -DsuiteXmlFile=src/test/resources/testng.xml | tee build.log
      shell: bash

    # Step 4: Debug the generated XLSX files
    - name: Debug the XLSX files
      run: |
        echo "Checking if the DE file exists and is not empty"
        ls -lh src/test/resources/DE_HomePage.xlsx
        echo "Checking if the EN file exists and is not empty"
        ls -lh src/test/resources/EN_HomePage.xlsx

    # Step 5: Upload Test Results and Logs
    - name: Upload Test Results and Logs
      if: always() # Ensure this step runs even if tests fail
      uses: actions/upload-artifact@v3
      with:
        name: test-results-and-logs
        path: |
          src/test/resources/DE_HomePage.xlsx
          src/test/resources/EN_HomePage.xlsx
          build.log

    # Step 6: Print Artifact URL
    - name: Generate Artifact Download URL
      if: always()
      run: |
        echo "Artifacts are available here:"
        echo "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
