name: Java CI with Maven

on:
  schedule:
    - cron: "30 0 * * *"  # 6:00 AM IST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - uses: actions/checkout@v4

    # Step 2: Set up JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    # Step 3: Run Maven Test and Capture Logs
    - name: Run Maven Test with Logs
      run: |
        mvn clean test -DsuiteXmlFile=src/test/resources/testng.xml | tee build.log
      shell: bash

    # Step 4: Upload Artifacts
    - name: Upload Test Results and Logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results-and-logs
        path: |
          src/test/resources/DE_HomePage.xlsx
          src/test/resources/EN_HomePage.xlsx
          build.log

    # Step 5: Generate Artifact Download URL
    - name: Generate Artifact Download Link
      if: always()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Fetching artifacts..."
        ARTIFACT_URL=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
        "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts" \
        | jq -r '.artifacts[] | select(.name=="test-results-and-logs") | .archive_download_url')

        if [ -z "$ARTIFACT_URL" ]; then
          echo "Failed to fetch artifact URL."
          exit 1
        fi
        
        echo "Artifact download link (no sign-in required):"
        echo "$ARTIFACT_URL"
