name: Java CI with Maven

on:
  schedule:
    - cron: "30 0 * * *"  # 6:00 AM IST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Run Specific Test
      run: mvn -Dtest=com.nn.testcase.homepage.HomePageTest test
